// Code generated by sqlc. DO NOT EDIT.

package dal

import (
	"github.com/brevis-network/uniswap-rebate/binding"
)

type Monitor struct {
	Key    string `json:"key"`
	Blknum uint64 `json:"blknum"`
	Blkidx int64  `json:"blkidx"`
}

type Pool struct {
	Chid    uint64          `json:"chid"`
	Poolid  string          `json:"poolid"`
	Poolkey binding.PoolKey `json:"poolkey"`
}

type Req struct {
	ID       int64            `json:"id"`
	Step     int32            `json:"step"`
	Txs      []string         `json:"txs"`
	Calldata binding.CallData `json:"calldata"`
}
