// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dal

import (
	"github.com/brevis-network/uniswap-rebate/binding"
	"github.com/brevis-network/uniswap-rebate/webapi"
)

type Claimer struct {
	Chid   uint64                   `json:"chid"`
	Router string                   `json:"router"`
	Evlog  binding.ClaimHelpClaimer `json:"evlog"`
}

type Monitor struct {
	Key    string `json:"key"`
	Blknum uint64 `json:"blknum"`
	Blkidx int64  `json:"blkidx"`
}

type Pool struct {
	Chid    uint64          `json:"chid"`
	Poolid  string          `json:"poolid"`
	Poolkey binding.PoolKey `json:"poolkey"`
}

type Req struct {
	ID       int64               `json:"id"`
	Step     int32               `json:"step"`
	Proofreq *webapi.NewProofReq `json:"proofreq"`
	Calldata binding.CallData    `json:"calldata"`
}
