// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dal

import (
	"github.com/brevis-network/brevis-sdk/sdk/proto/commonproto"
	"github.com/brevis-network/brevis-sdk/sdk/proto/gwproto"
	"github.com/brevis-network/uniswap-rebate/binding"
	"github.com/brevis-network/uniswap-rebate/webapi"
)

type Claimer struct {
	Chid   uint64                   `json:"chid"`
	Router string                   `json:"router"`
	Evlog  binding.ClaimHelpClaimer `json:"evlog"`
}

type Monitor struct {
	Key    string `json:"key"`
	Blknum uint64 `json:"blknum"`
	Blkidx int64  `json:"blkidx"`
}

type Pool struct {
	Chid    uint64          `json:"chid"`
	Poolid  string          `json:"poolid"`
	Poolkey binding.PoolKey `json:"poolkey"`
}

type Proof struct {
	Reqid              int64                           `json:"reqid"`
	Idx                int                             `json:"idx"`
	AppProver          string                          `json:"appProver"`
	AppProofID         string                          `json:"appProofId"`
	AppCircuitInfo     *commonproto.AppCircuitInfo     `json:"appCircuitInfo"`
	AppProof           string                          `json:"appProof"`
	GatewayBatchID     string                          `json:"gatewayBatchId"`
	GatewayRequestID   string                          `json:"gatewayRequestId"`
	GatewayNonce       uint64                          `json:"gatewayNonce"`
	GatewayQueryStatus *gwproto.GetQueryStatusResponse `json:"gatewayQueryStatus"`
}

type Req struct {
	ID        int64               `json:"id"`
	Router    string              `json:"router"`
	Step      int32               `json:"step"`
	UsrReq    *webapi.NewProofReq `json:"usrReq"`
	ProofInfo binding.ProofInfo   `json:"proofInfo"`
	Calldata  binding.CallData    `json:"calldata"`
}
