db = "localhost:26257"
httpport = 9002 # serving rest apis
# send reqs to prove server which generates app proof then submit to brv gateway
prover = "http://localhost:9003"

[[multichain]]
chainID = 11155111
name = "Sepolia"
gateway = "https://sepolia.drpc.org"
BlkInterval = 12
BlkDelay = 2

GasPerSwap = 80000
GasPerTx = 80000
PoolMgr = "0x8C4BcBE6b9eF47855f97E675296FA3F6fafa5F1A"
VkHash = ""
