db = "localhost:26257"
grpcport = 9001
httpport = 9002
# send reqs to prove server which generates app proof then submit to brv gateway
prover = "http://localhost:8889"

[[multichain]]
chainID = 11155111
name = "Sepolia"
gateway = "https://sepolia.infura.io/v3/701edff6e8eb44c1b4e3fe36ee2b23fc"
BlkInterval = 12
BlkDelay = 2

GasPerSwap = 80000
PoolMgr = "0x8C4BcBE6b9eF47855f97E675296FA3F6fafa5F1A"
Oracle = "0xc8caf3c1d76d264b6d5d511d883b58b3874eafa0"
VkHash = ""