db = "localhost:26257"
httpport = 9002 # serving rest apis
brvgw = "52.13.236.124:11080" # dns:port or ip:port of brevis gateway
# list of app provers, each runs prover/main.go 
prover = ["localhost:9001"]
# chainid of gas rebate contract, should be 130 Unichain mainnet for prod
dstchid = 130
beneficiary_registry = "0x28C0d8BCb791E8582F687d9d62396bA7A92a474E"
prove_interval = "5m"

[[multichain]]
chainID = 11155111
name = "Sepolia"
gateway = "https://sepolia.drpc.org"
BlkInterval = 12
BlkDelay = 2

GasPerSwap = 80000
GasPerTx = 80000
PoolMgr = "0xE03A1074c86CFeDd5C142C4F04F1a1536e203543"
VkHash = ""

[[multichain]]
chainID = 130
name = "Unichain"
gateway = "https://mainnet.unichain.org"
BlkInterval = 12
BlkDelay = 2

GasPerSwap = 80000
GasPerTx = 80000
PoolMgr = "0x0000000000000000000000000000000000000000"
VkHash = ""
