db = "localhost:26257"
httpport = 9002 # serving rest apis
brvgw = "52.13.236.124:11080" # dns:port or ip:port of brevis gateway
# list of app provers, each runs prover/main.go 
prover = ["localhost:9001"]
# chainid of gas rebate contract, should be 130 Unichain mainnet for prod
dstchid = 130

[[multichain]]
chainID = 11155111
name = "Sepolia"
gateway = "https://sepolia.drpc.org"
BlkInterval = 12
BlkDelay = 2

GasPerSwap = 80000
GasPerTx = 80000
PoolMgr = "0x8C4BcBE6b9eF47855f97E675296FA3F6fafa5F1A"
VkHash = ""
