// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: webapi.proto

package webapi

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// sign?chainId=1&campaignId=1&txnHashes=0x123,0x456
// we have to be compatible w/ uni's impl, so txnHashes can't be repeated
type NewProofReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       uint64                 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	TxnHashes     string                 `protobuf:"bytes,2,opt,name=txn_hashes,json=txnHashes,proto3" json:"txn_hashes,omitempty"` // comma separated tx hashes
	Beneficiary   string                 `protobuf:"bytes,3,opt,name=beneficiary,proto3" json:"beneficiary,omitempty"`              // router contract addr
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewProofReq) Reset() {
	*x = NewProofReq{}
	mi := &file_webapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewProofReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewProofReq) ProtoMessage() {}

func (x *NewProofReq) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewProofReq.ProtoReflect.Descriptor instead.
func (*NewProofReq) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{0}
}

func (x *NewProofReq) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *NewProofReq) GetTxnHashes() string {
	if x != nil {
		return x.TxnHashes
	}
	return ""
}

func (x *NewProofReq) GetBeneficiary() string {
	if x != nil {
		return x.Beneficiary
	}
	return ""
}

type NewProofResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reqid         uint64                 `protobuf:"varint,1,opt,name=reqid,proto3" json:"reqid,omitempty"`  // unique id for later query
	Errmsg        string                 `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"` // if runinto any err, reqid will be 0 and err details in errmsg
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewProofResp) Reset() {
	*x = NewProofResp{}
	mi := &file_webapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewProofResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewProofResp) ProtoMessage() {}

func (x *NewProofResp) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewProofResp.ProtoReflect.Descriptor instead.
func (*NewProofResp) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{1}
}

func (x *NewProofResp) GetReqid() uint64 {
	if x != nil {
		return x.Reqid
	}
	return 0
}

func (x *NewProofResp) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

type GetProofReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reqid         uint64                 `protobuf:"varint,1,opt,name=reqid,proto3" json:"reqid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProofReq) Reset() {
	*x = GetProofReq{}
	mi := &file_webapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProofReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProofReq) ProtoMessage() {}

func (x *GetProofReq) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProofReq.ProtoReflect.Descriptor instead.
func (*GetProofReq) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{2}
}

func (x *GetProofReq) GetReqid() uint64 {
	if x != nil {
		return x.Reqid
	}
	return 0
}

type GetProofResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reqid         uint64                 `protobuf:"varint,1,opt,name=reqid,proto3" json:"reqid,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // info about this req, eg. which step, any err
	Calldata      *CallData              `protobuf:"bytes,3,opt,name=calldata,proto3" json:"calldata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProofResp) Reset() {
	*x = GetProofResp{}
	mi := &file_webapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProofResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProofResp) ProtoMessage() {}

func (x *GetProofResp) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProofResp.ProtoReflect.Descriptor instead.
func (*GetProofResp) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{3}
}

func (x *GetProofResp) GetReqid() uint64 {
	if x != nil {
		return x.Reqid
	}
	return 0
}

func (x *GetProofResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetProofResp) GetCalldata() *CallData {
	if x != nil {
		return x.Calldata
	}
	return nil
}

type CallData struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProofIds          []string               `protobuf:"bytes,1,rep,name=proof_ids,json=proofIds,proto3" json:"proof_ids,omitempty"` // each string is hex of [32]byte
	Proof             string                 `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`                       // hex of []byte
	ProofDataArray    []*BrevisProofData     `protobuf:"bytes,3,rep,name=proof_data_array,json=proofDataArray,proto3" json:"proof_data_array,omitempty"`
	AppCircuitOutputs []string               `protobuf:"bytes,4,rep,name=app_circuit_outputs,json=appCircuitOutputs,proto3" json:"app_circuit_outputs,omitempty"` // each string is hex of []byte
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CallData) Reset() {
	*x = CallData{}
	mi := &file_webapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallData) ProtoMessage() {}

func (x *CallData) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallData.ProtoReflect.Descriptor instead.
func (*CallData) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{4}
}

func (x *CallData) GetProofIds() []string {
	if x != nil {
		return x.ProofIds
	}
	return nil
}

func (x *CallData) GetProof() string {
	if x != nil {
		return x.Proof
	}
	return ""
}

func (x *CallData) GetProofDataArray() []*BrevisProofData {
	if x != nil {
		return x.ProofDataArray
	}
	return nil
}

func (x *CallData) GetAppCircuitOutputs() []string {
	if x != nil {
		return x.AppCircuitOutputs
	}
	return nil
}

// each field is hex of [32]byte
type BrevisProofData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommitHash    string                 `protobuf:"bytes,1,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	AppCommitHash string                 `protobuf:"bytes,2,opt,name=app_commit_hash,json=appCommitHash,proto3" json:"app_commit_hash,omitempty"`
	AppVkHash     string                 `protobuf:"bytes,3,opt,name=app_vk_hash,json=appVkHash,proto3" json:"app_vk_hash,omitempty"`
	SmtRoot       string                 `protobuf:"bytes,4,opt,name=smt_root,json=smtRoot,proto3" json:"smt_root,omitempty"`
	DummyInput    string                 `protobuf:"bytes,5,opt,name=dummy_input,json=dummyInput,proto3" json:"dummy_input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrevisProofData) Reset() {
	*x = BrevisProofData{}
	mi := &file_webapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrevisProofData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrevisProofData) ProtoMessage() {}

func (x *BrevisProofData) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrevisProofData.ProtoReflect.Descriptor instead.
func (*BrevisProofData) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{5}
}

func (x *BrevisProofData) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *BrevisProofData) GetAppCommitHash() string {
	if x != nil {
		return x.AppCommitHash
	}
	return ""
}

func (x *BrevisProofData) GetAppVkHash() string {
	if x != nil {
		return x.AppVkHash
	}
	return ""
}

func (x *BrevisProofData) GetSmtRoot() string {
	if x != nil {
		return x.SmtRoot
	}
	return ""
}

func (x *BrevisProofData) GetDummyInput() string {
	if x != nil {
		return x.DummyInput
	}
	return ""
}

var File_webapi_proto protoreflect.FileDescriptor

const file_webapi_proto_rawDesc = "" +
	"\n" +
	"\fwebapi.proto\x1a\x1cgoogle/api/annotations.proto\"i\n" +
	"\vNewProofReq\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x04R\achainId\x12\x1d\n" +
	"\n" +
	"txn_hashes\x18\x02 \x01(\tR\ttxnHashes\x12 \n" +
	"\vbeneficiary\x18\x03 \x01(\tR\vbeneficiary\"<\n" +
	"\fNewProofResp\x12\x14\n" +
	"\x05reqid\x18\x01 \x01(\x04R\x05reqid\x12\x16\n" +
	"\x06errmsg\x18\x02 \x01(\tR\x06errmsg\"#\n" +
	"\vGetProofReq\x12\x14\n" +
	"\x05reqid\x18\x01 \x01(\x04R\x05reqid\"c\n" +
	"\fGetProofResp\x12\x14\n" +
	"\x05reqid\x18\x01 \x01(\x04R\x05reqid\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12%\n" +
	"\bcalldata\x18\x03 \x01(\v2\t.CallDataR\bcalldata\"\xa9\x01\n" +
	"\bCallData\x12\x1b\n" +
	"\tproof_ids\x18\x01 \x03(\tR\bproofIds\x12\x14\n" +
	"\x05proof\x18\x02 \x01(\tR\x05proof\x12:\n" +
	"\x10proof_data_array\x18\x03 \x03(\v2\x10.BrevisProofDataR\x0eproofDataArray\x12.\n" +
	"\x13app_circuit_outputs\x18\x04 \x03(\tR\x11appCircuitOutputs\"\xb6\x01\n" +
	"\x0fBrevisProofData\x12\x1f\n" +
	"\vcommit_hash\x18\x01 \x01(\tR\n" +
	"commitHash\x12&\n" +
	"\x0fapp_commit_hash\x18\x02 \x01(\tR\rappCommitHash\x12\x1e\n" +
	"\vapp_vk_hash\x18\x03 \x01(\tR\tappVkHash\x12\x19\n" +
	"\bsmt_root\x18\x04 \x01(\tR\asmtRoot\x12\x1f\n" +
	"\vdummy_input\x18\x05 \x01(\tR\n" +
	"dummyInput2\x87\x01\n" +
	"\tUniRebate\x128\n" +
	"\bNewProof\x12\f.NewProofReq\x1a\r.NewProofResp\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/zk/new\x12@\n" +
	"\bGetProof\x12\f.GetProofReq\x1a\r.GetProofResp\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/zk/get/{reqid}B1Z/github.com/brevis-network/uniswap-rebate/webapib\x06proto3"

var (
	file_webapi_proto_rawDescOnce sync.Once
	file_webapi_proto_rawDescData []byte
)

func file_webapi_proto_rawDescGZIP() []byte {
	file_webapi_proto_rawDescOnce.Do(func() {
		file_webapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_webapi_proto_rawDesc), len(file_webapi_proto_rawDesc)))
	})
	return file_webapi_proto_rawDescData
}

var file_webapi_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_webapi_proto_goTypes = []any{
	(*NewProofReq)(nil),     // 0: NewProofReq
	(*NewProofResp)(nil),    // 1: NewProofResp
	(*GetProofReq)(nil),     // 2: GetProofReq
	(*GetProofResp)(nil),    // 3: GetProofResp
	(*CallData)(nil),        // 4: CallData
	(*BrevisProofData)(nil), // 5: BrevisProofData
}
var file_webapi_proto_depIdxs = []int32{
	4, // 0: GetProofResp.calldata:type_name -> CallData
	5, // 1: CallData.proof_data_array:type_name -> BrevisProofData
	0, // 2: UniRebate.NewProof:input_type -> NewProofReq
	2, // 3: UniRebate.GetProof:input_type -> GetProofReq
	1, // 4: UniRebate.NewProof:output_type -> NewProofResp
	3, // 5: UniRebate.GetProof:output_type -> GetProofResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_webapi_proto_init() }
func file_webapi_proto_init() {
	if File_webapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webapi_proto_rawDesc), len(file_webapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_webapi_proto_goTypes,
		DependencyIndexes: file_webapi_proto_depIdxs,
		MessageInfos:      file_webapi_proto_msgTypes,
	}.Build()
	File_webapi_proto = out.File
	file_webapi_proto_goTypes = nil
	file_webapi_proto_depIdxs = nil
}
