// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v4.24.3
// source: webapi.proto

package webapi

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// sign?chainId=1&campaignId=1&txnHashes=0x123,0x456
// we have to be compatible w/ uni's impl, so txnHashes can't be repeated
type NewProofReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainId    uint64 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	CampaignId uint64 `protobuf:"varint,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"` // will be ignored as zk doesn't support campaign
	TxnHashes  string `protobuf:"bytes,3,opt,name=txn_hashes,json=txnHashes,proto3" json:"txn_hashes,omitempty"`
}

func (x *NewProofReq) Reset() {
	*x = NewProofReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewProofReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewProofReq) ProtoMessage() {}

func (x *NewProofReq) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewProofReq.ProtoReflect.Descriptor instead.
func (*NewProofReq) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{0}
}

func (x *NewProofReq) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *NewProofReq) GetCampaignId() uint64 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *NewProofReq) GetTxnHashes() string {
	if x != nil {
		return x.TxnHashes
	}
	return ""
}

type NewProofResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reqid  uint64 `protobuf:"varint,1,opt,name=reqid,proto3" json:"reqid,omitempty"`  // unique id for later query
	Errmsg string `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"` // if runinto any err, reqid will be 0 and err details in errmsg
}

func (x *NewProofResp) Reset() {
	*x = NewProofResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewProofResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewProofResp) ProtoMessage() {}

func (x *NewProofResp) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewProofResp.ProtoReflect.Descriptor instead.
func (*NewProofResp) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{1}
}

func (x *NewProofResp) GetReqid() uint64 {
	if x != nil {
		return x.Reqid
	}
	return 0
}

func (x *NewProofResp) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

type GetProofReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reqid uint64 `protobuf:"varint,1,opt,name=reqid,proto3" json:"reqid,omitempty"`
}

func (x *GetProofReq) Reset() {
	*x = GetProofReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProofReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProofReq) ProtoMessage() {}

func (x *GetProofReq) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProofReq.ProtoReflect.Descriptor instead.
func (*GetProofReq) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{2}
}

func (x *GetProofReq) GetReqid() uint64 {
	if x != nil {
		return x.Reqid
	}
	return 0
}

type GetProofResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reqid    uint64    `protobuf:"varint,1,opt,name=reqid,proto3" json:"reqid,omitempty"`
	Status   string    `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // info about this req, eg. which step, any err
	Calldata *CallData `protobuf:"bytes,3,opt,name=calldata,proto3" json:"calldata,omitempty"`
}

func (x *GetProofResp) Reset() {
	*x = GetProofResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProofResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProofResp) ProtoMessage() {}

func (x *GetProofResp) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProofResp.ProtoReflect.Descriptor instead.
func (*GetProofResp) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{3}
}

func (x *GetProofResp) GetReqid() uint64 {
	if x != nil {
		return x.Reqid
	}
	return 0
}

func (x *GetProofResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetProofResp) GetCalldata() *CallData {
	if x != nil {
		return x.Calldata
	}
	return nil
}

type CallData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProofIds          []string           `protobuf:"bytes,1,rep,name=proof_ids,json=proofIds,proto3" json:"proof_ids,omitempty"` // each string is hex of [32]byte
	Proof             string             `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`                       // hex of []byte
	ProofDataArray    []*BrevisProofData `protobuf:"bytes,3,rep,name=proof_data_array,json=proofDataArray,proto3" json:"proof_data_array,omitempty"`
	AppCircuitOutputs []string           `protobuf:"bytes,4,rep,name=app_circuit_outputs,json=appCircuitOutputs,proto3" json:"app_circuit_outputs,omitempty"` // each string is hex of []byte
}

func (x *CallData) Reset() {
	*x = CallData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallData) ProtoMessage() {}

func (x *CallData) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallData.ProtoReflect.Descriptor instead.
func (*CallData) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{4}
}

func (x *CallData) GetProofIds() []string {
	if x != nil {
		return x.ProofIds
	}
	return nil
}

func (x *CallData) GetProof() string {
	if x != nil {
		return x.Proof
	}
	return ""
}

func (x *CallData) GetProofDataArray() []*BrevisProofData {
	if x != nil {
		return x.ProofDataArray
	}
	return nil
}

func (x *CallData) GetAppCircuitOutputs() []string {
	if x != nil {
		return x.AppCircuitOutputs
	}
	return nil
}

type BrevisProofData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommitHash    string `protobuf:"bytes,1,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	VkHash        string `protobuf:"bytes,2,opt,name=vk_hash,json=vkHash,proto3" json:"vk_hash,omitempty"`
	AppCommitHash string `protobuf:"bytes,3,opt,name=app_commit_hash,json=appCommitHash,proto3" json:"app_commit_hash,omitempty"`
	AppVkHash     string `protobuf:"bytes,4,opt,name=app_vk_hash,json=appVkHash,proto3" json:"app_vk_hash,omitempty"`
	SmtRoot       string `protobuf:"bytes,5,opt,name=smt_root,json=smtRoot,proto3" json:"smt_root,omitempty"`
}

func (x *BrevisProofData) Reset() {
	*x = BrevisProofData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrevisProofData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrevisProofData) ProtoMessage() {}

func (x *BrevisProofData) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrevisProofData.ProtoReflect.Descriptor instead.
func (*BrevisProofData) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{5}
}

func (x *BrevisProofData) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *BrevisProofData) GetVkHash() string {
	if x != nil {
		return x.VkHash
	}
	return ""
}

func (x *BrevisProofData) GetAppCommitHash() string {
	if x != nil {
		return x.AppCommitHash
	}
	return ""
}

func (x *BrevisProofData) GetAppVkHash() string {
	if x != nil {
		return x.AppVkHash
	}
	return ""
}

func (x *BrevisProofData) GetSmtRoot() string {
	if x != nil {
		return x.SmtRoot
	}
	return ""
}

var File_webapi_proto protoreflect.FileDescriptor

var file_webapi_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x77, 0x65, 0x62, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x68, 0x0a, 0x0b,
	0x4e, 0x65, 0x77, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69,
	0x67, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x63, 0x61, 0x6d,
	0x70, 0x61, 0x69, 0x67, 0x6e, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x78, 0x6e, 0x5f, 0x68,
	0x61, 0x73, 0x68, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x78, 0x6e,
	0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x22, 0x3c, 0x0a, 0x0c, 0x4e, 0x65, 0x77, 0x50, 0x72, 0x6f,
	0x6f, 0x66, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x71, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x72, 0x65, 0x71, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72,
	0x72, 0x6d, 0x73, 0x67, 0x22, 0x23, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x6f, 0x66,
	0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x71, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x72, 0x65, 0x71, 0x69, 0x64, 0x22, 0x63, 0x0a, 0x0c, 0x47, 0x65, 0x74,
	0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x71,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x72, 0x65, 0x71, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x43, 0x61, 0x6c, 0x6c,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x64, 0x61, 0x74, 0x61, 0x22, 0xa9,
	0x01, 0x0a, 0x08, 0x43, 0x61, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x70,
	0x72, 0x6f, 0x6f, 0x66, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x72, 0x6f, 0x6f, 0x66, 0x49, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x6f,
	0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x3a,
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x61, 0x72, 0x72,
	0x61, 0x79, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x42, 0x72, 0x65, 0x76, 0x69,
	0x73, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x6f,
	0x66, 0x44, 0x61, 0x74, 0x61, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x2e, 0x0a, 0x13, 0x61, 0x70,
	0x70, 0x5f, 0x63, 0x69, 0x72, 0x63, 0x75, 0x69, 0x74, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x11, 0x61, 0x70, 0x70, 0x43, 0x69, 0x72, 0x63,
	0x75, 0x69, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x22, 0xae, 0x01, 0x0a, 0x0f, 0x42,
	0x72, 0x65, 0x76, 0x69, 0x73, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1f,
	0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12,
	0x17, 0x0a, 0x07, 0x76, 0x6b, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x76, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12, 0x26, 0x0a, 0x0f, 0x61, 0x70, 0x70, 0x5f,
	0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x61, 0x70, 0x70, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x1e, 0x0a, 0x0b, 0x61, 0x70, 0x70, 0x5f, 0x76, 0x6b, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x70, 0x70, 0x56, 0x6b, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x19, 0x0a, 0x08, 0x73, 0x6d, 0x74, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x6d, 0x74, 0x52, 0x6f, 0x6f, 0x74, 0x32, 0x81, 0x01, 0x0a, 0x03,
	0x57, 0x65, 0x62, 0x12, 0x38, 0x0a, 0x08, 0x4e, 0x65, 0x77, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12,
	0x0c, 0x2e, 0x4e, 0x65, 0x77, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e,
	0x4e, 0x65, 0x77, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x65, 0x73, 0x70, 0x22, 0x0f, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x09, 0x12, 0x07, 0x2f, 0x7a, 0x6b, 0x2f, 0x6e, 0x65, 0x77, 0x12, 0x40, 0x0a,
	0x08, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x0c, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x72, 0x6f, 0x6f, 0x66, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f,
	0x6f, 0x66, 0x52, 0x65, 0x73, 0x70, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11, 0x12, 0x0f,
	0x2f, 0x7a, 0x6b, 0x2f, 0x67, 0x65, 0x74, 0x2f, 0x7b, 0x72, 0x65, 0x71, 0x69, 0x64, 0x7d, 0x42,
	0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x72,
	0x65, 0x76, 0x69, 0x73, 0x2d, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x75, 0x6e, 0x69,
	0x73, 0x77, 0x61, 0x70, 0x2d, 0x72, 0x65, 0x62, 0x61, 0x74, 0x65, 0x2f, 0x77, 0x65, 0x62, 0x61,
	0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_webapi_proto_rawDescOnce sync.Once
	file_webapi_proto_rawDescData = file_webapi_proto_rawDesc
)

func file_webapi_proto_rawDescGZIP() []byte {
	file_webapi_proto_rawDescOnce.Do(func() {
		file_webapi_proto_rawDescData = protoimpl.X.CompressGZIP(file_webapi_proto_rawDescData)
	})
	return file_webapi_proto_rawDescData
}

var file_webapi_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_webapi_proto_goTypes = []interface{}{
	(*NewProofReq)(nil),     // 0: NewProofReq
	(*NewProofResp)(nil),    // 1: NewProofResp
	(*GetProofReq)(nil),     // 2: GetProofReq
	(*GetProofResp)(nil),    // 3: GetProofResp
	(*CallData)(nil),        // 4: CallData
	(*BrevisProofData)(nil), // 5: BrevisProofData
}
var file_webapi_proto_depIdxs = []int32{
	4, // 0: GetProofResp.calldata:type_name -> CallData
	5, // 1: CallData.proof_data_array:type_name -> BrevisProofData
	0, // 2: Web.NewProof:input_type -> NewProofReq
	2, // 3: Web.GetProof:input_type -> GetProofReq
	1, // 4: Web.NewProof:output_type -> NewProofResp
	3, // 5: Web.GetProof:output_type -> GetProofResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_webapi_proto_init() }
func file_webapi_proto_init() {
	if File_webapi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_webapi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewProofReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webapi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewProofResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webapi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProofReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webapi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProofResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webapi_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webapi_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrevisProofData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_webapi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_webapi_proto_goTypes,
		DependencyIndexes: file_webapi_proto_depIdxs,
		MessageInfos:      file_webapi_proto_msgTypes,
	}.Build()
	File_webapi_proto = out.File
	file_webapi_proto_rawDesc = nil
	file_webapi_proto_goTypes = nil
	file_webapi_proto_depIdxs = nil
}
